version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./config:/etc/traefik/config
      - ./ssl:/etc/traefik/ssl

    networks:
      - proxy-manager-net

networks:
  proxy-manager-net:
    name: proxy-manager-net
    external: true

